export const USER_SIGNIN_SUCCESS="USER_SIGNIN_SUCCESS"
export const USER_SIGNUP_SUCCESS="USER_SIGNUP_SUCCESS"
export const SIGNUP_REQUEST="SIGNUP_REQUEST"
export const SIGNUP_SUCCESS="SIGNUP_SUCCESS"
export const USER_LOGOUT="USER_LOGOUT"

export const GETLIVECARDS="GETLIVECARDS"